name: CMake

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - 'v*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HOST: [ x86_64-linux-musl, i686-linux-musl, aarch64-linux-musl, arm-linux-musleabihf ]

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y meson qemu-user qemu-user-binfmt

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/toolchains/${{ matrix.HOST }}.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        if: (matrix.HOST == 'x86_64-linux-musl') || (matrix.HOST == 'i686-linux-musl')
        working-directory: ${{github.workspace}}/build
        run: src/runtime --appimage-help

      - name: Prepare artifact
        run: mv ${{github.workspace}}/build/src/runtime runtime-${{ matrix.HOST }}

      - uses: actions/upload-artifact@v3
        with:
          name: runtime
          path: runtime-${{ matrix.HOST }}